### ISSUE TITLE
Extract Test 

### ISSUE THREAD

**Issue by AngeloVenera** [omeka-s-modules/ExtractText#3]
Hi At all

two issue, the first is, in the file module.ini the environment "omeka_version_constraint" must be "^1.3.0" don't "^1.4.0" the latest version of omeka-s is 1.3.0. The second is, where can i found the application for "DOCX (application/vnd.openxmlformats-officedocument.wordprocessingml.document)" what is or what are the utility for this application? 

Thank you for all, Angelo

**Comment by jimsafley** [comment]
ExtractText was mistakenly published on the modules page before it was ready for release. We have since taken it down. It does indeed require Omeka S v1.4.0, which is still under development. You can find information on all dependencies on the module's [README](https://github.com/omeka-s-modules/ExtractText/blob/master/README.md).
