### ISSUE TITLE
Testing: Tesseract extractor

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ExtractText#7]
The [tesseract](https://github.com/omeka-s-modules/ExtractText/compare/tesseract) branch adds the "tesseract" extractor which performs automatic text recognition on image files. Tesseract often takes a long time to process images—too long for the browser to wait for the process to finish—so this branch also adds the ability to extract text asynchronously in a background job. You can read more about this in the [README](https://github.com/omeka-s-modules/ExtractText/tree/tesseract#long-running-extraction).

To test this, when editing an item, upload a few images of printed text, like historic newspapers and documents. Edit the item again, go to the "Extract text" tab, and select "Refresh text (background)". Save the item. Behind the scenes, this should dispatch a background job that runs tesseract on the images. You can navigate to the "Jobs" page and see the "ExtractText\Job\RefreshItemText" job, which is "In progress" or "Completed." Once it's completed go back to the item and you should see extracted text in the "extracted text" property.

**Comment by allanaaa** [comment]
This worked very well on the two images I tested. 

I note that there is no way to turn off Tesseract in the settings, or to choose which media get processed when in the item editing interface. Do we want to offer this so that non-text images aren't getting unduly processed? As you say, running this will be resource intensive. 

Users might have a multi-file item where they only want to process one or select media, not all of them, or only certain media by type, etc.

I realize you have instructions on how to turn Tesseract etc. off in the config files, but since we have a Configuration page and a table already there, perhaps an on/off switch won't be too hard to add. That setting would, I think, cover all the CSV Import processing. The item-editing tab could just list all the media currently attached and a checkbox for each. 

Side question: I would prefer Extract Text generate a separate metadata value for each media. Any chance of that?

**Comment by allanaaa** [comment]
An interface setting for Tesseract's language would be great, too.

**Comment by allanaaa** [comment]
I assume when you use batch-editing to refresh text on multiple items, it already runs as a background job? I realize it doesn't show up on the Jobs page but I assume otherwise it's the same.

**Comment by jimsafley** [comment]
> Users might have a multi-file item where they only want to process one or select media, not all of them, or only certain media by type, etc.

To address this I've made it possible for users to extract text from individual media. Edit a media and go to the "Extract text" tab. It's an identical interface to the item edit's "Extract text" tab. Pull the changes and test it out. You should probably give the module another comprehensive test, given how many changes were needed to add this feature. 

> I realize you have instructions on how to turn Tesseract etc. off in the config files, but since we have a Configuration page and a table already there, perhaps an on/off switch won't be too hard to add.

It's a good idea. I'll look into adding an on/off toggle for the extractors on the module config page.

> Side question: I would prefer Extract Text generate a separate metadata value for each media. Any chance of that?

An interesting request, but difficult to implement, especially considering the migration that would be necessary when moving to separate values. I'll think about it.

> An interface setting for Tesseract's language would be great, too.

Another good idea, but harder to implement. I'll look into it. For the time being, users can configure Tesseract's language in module.config.php under `[extract_text][options][tesseract][l]`.

> I assume when you use batch-editing to refresh text on multiple items, it already runs as a background job?

An "Edit selected" batch runs in the foreground. An "Edit all" batch runs in the background. Background-only extractors will only run during an "Edit all" batch. I'm not including the "Refresh text (background)" in the batch form because I don't want to risk firing off multiple jobs on one request.

**Comment by allanaaa** [comment]
> An "Edit selected" batch runs in the foreground. An "Edit all" batch runs in the background. Background-only extractors will only run during an "Edit all" batch. I'm not including the "Refresh text (background)" in the batch form because I don't want to risk firing off multiple jobs on one request.

That makes sense. I was thinking more of "What logs as a Job" from the perspective of a user - editing a single item seems to make less sense than batch edits. I suppose we can specify that stuff in the docs though.

**Comment by jimsafley** [comment]
I've added the ability to disable individual extractors in the the module config page. Pull and try it out.

**Comment by allanaaa** [comment]
Thanks. Disabling tesseract, then disabling PDFtotext, and re-enabling, worked well. CSV Import with different things disabled worked well too. 

So, for the docs: 

Tesseract is unique in that it only works as a background job. It won't work on manual file upload, but it will work using CSV Import. If you have images to process, you have to select "Refresh text (background)" - selecting "Refresh text" on the item won't run Tesseract, but will run every other enabled processor. 

I think this can all be explained in the docs, but I wonder if we can improve the interface too. Since "(background)" is (so far) exclusively for Tesseract, can we just say that instead? "Refresh text (with Tesseract)" or something?

**Comment by jimsafley** [comment]
> Since "(background)" is (so far) exclusively for Tesseract, can we just say that instead? "Refresh text (with Tesseract)" or something?

This got me thinking about another approach to background support. Now, on the module config page, administrators can set individual extractors to only run in the background. Tesseract is the only extractor that is background only by default. Pull and try it out.

**Comment by allanaaa** [comment]
Neat, everything works as expected. 

So this means that Tesseract *can* run in the foreground, even though we really don't recommend it. Or should the option be greyed out? Or maybe just add some help text like "We recommend Tesseract be run as a background task only." 

Again, summarizing for the docs - let me know if any of this isn't quite right: 

You can set any of the extractors to run only as a background job. This will log a Job with ID in the Jobs page. When extractors are set as background only, they will only run at an item level when "Refresh text (background)" is selected. They will not run automatically when a new file is uploaded. They will run on CSV Import processes.

When "Background only" is not checked, the extractor will run on file upload, on "Refresh text", and on "Refresh text (background)". 

When batch-editing multiple items, an "Edit selected" batch runs in the foreground. An "Edit all" batch runs in the background. Background-only extractors will only run during an "Edit all" batch.

We recommend only running Tesseract as a background task. Depending on the size of your other files, such as PDFs, you may wish to set other extractors to run in the background only.

**Comment by jimsafley** [comment]
> So this means that Tesseract can run in the foreground, even though we really don't recommend it. Or should the option be greyed out? Or maybe just add some help text like "We recommend Tesseract be run as a background task only."

It's a good idea to prevent users from ever allowing foreground use of certain extractors. I've made it possible via a "extract_text/background_only" configuration in module.config.php. I've updated the README to reflect this.

**Comment by jimsafley** [comment]
Note that I've merged the `tesseract` branch into `master`, so you'll need to do further testing on that.
